/* Project Euler: Problem 2: Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence that do not exceed the nth term, find the sum of the even-valued terms.
*/

function fiboEvenSum(n) {
  // You can do it!
  var sum = 0;
  var fib1 = 0;
  var fib2 = 1;
  var next = 1;

  for(var i = 0; i <= n; i++) {
    next = fib1 + fib2;
    fib1 = fib2;
    fib2 = next;
    if(fib1 % 2 === 0) {
      sum += fib1;
    }
    
  }
  console.log(sum);
  return sum;
}

fiboEvenSum(23);